name: Docker

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
       
      - name: Authenticate with GitHub Container Registry
        run: echo "${{ github.token }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        
      - name: Build and Push Docker Image
        run: |
          docker buildx build . \
          --platform linux/amd64,linux/arm64 \
          --output type=registry \
          --tag ghcr.io/HazyFish/schedule-webapi:latest
